services:
  - type: web
    name: ryvr-api
    env: python
    plan: starter
    buildCommand: find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true && find . -type f -name "*.pyc" -delete 2>/dev/null || true && pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1440
      - key: OPENAI_API_KEY
        sync: false
      - key: DATAFORSEO_USERNAME
        sync: false
      - key: DATAFORSEO_PASSWORD
        sync: false
      - key: DATAFORSEO_BASE_URL
        value: https://sandbox.dataforseo.com
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false 